// ==========================================
// AUTO-GENERATED SKELETON FOR NODE: tube_render
// ==========================================

struct CameraStruct {
    viewProjection: mat4x4<f32>,
    view: mat4x4<f32>,
};

@group(0) @binding(0) var<uniform> camera: CameraStruct;
@group(0) @binding(1) var<storage, read> instances: array<f32>;
@group(0) @binding(2) var<storage, read> vertexData: array<f32>;

// ==========================================
// IMPLEMENT YOUR LOGIC BELOW
// ==========================================

struct VertexOutput {
    @builtin(position) position: vec4<f32>,
    @location(0) normal: vec3<f32>,
    @location(1) color: vec4<f32>,
};

@vertex
fn vs_main(@builtin(vertex_index) v_idx: u32, @builtin(instance_index) i_idx: u32) -> VertexOutput {
    var out: VertexOutput;

    // 1. Read the raw vertex geometry
    let v_offset = v_idx * 6u;
    let v_pos = vec3<f32>(vertexData[v_offset], vertexData[v_offset + 1u], vertexData[v_offset + 2u]);
    let v_norm = vec3<f32>(vertexData[v_offset + 3u], vertexData[v_offset + 4u], vertexData[v_offset + 5u]);

    // 2. Read the 12 parameters generated by the compute shader
    let i_offset = i_idx * 12u;
    let pivot = vec3<f32>(instances[i_offset + 0u], instances[i_offset + 1u], instances[i_offset + 2u]);
    let string_vec = vec3<f32>(instances[i_offset + 3u], instances[i_offset + 4u], instances[i_offset + 5u]);
    let radius = instances[i_offset + 6u];
    // offset + 7u is padding
    let color = vec4<f32>(instances[i_offset + 8u], instances[i_offset + 9u], instances[i_offset + 10u], instances[i_offset + 11u]);

    // 3. Geometry Math (Scale & Rotate & Translate)
    let string_length = length(string_vec);
    
    // Scale the tube (X/Y by radius, Z by the actual string length)
    let scaled_pos = vec3<f32>(v_pos.x * radius, v_pos.y * radius, v_pos.z * string_length);

    // Build the Rotation Matrix
    let Z_prime = string_vec / string_length; // Normalized direction
    
    // Because the pendulum swings in the XY plane, Z is always 0, 
    // so using +Z (0,0,1) as our helper up-vector is 100% mathematically safe here.
    let helper_up = vec3<f32>(0.0, 0.0, 1.0); 
    
    let X_prime = normalize(cross(helper_up, Z_prime));
    let Y_prime = cross(Z_prime, X_prime);
    let rot_mat = mat3x3<f32>(X_prime, Y_prime, Z_prime);

    // Rotate and move to the pivot point
    let world_pos = (rot_mat * scaled_pos) + pivot;
    let world_norm = rot_mat * v_norm;

    // 4. Transform to camera space
    out.position = camera.viewProjection * vec4<f32>(world_pos, 1.0);
    out.normal = (camera.view * vec4<f32>(world_norm, 0.0)).xyz;
    out.color = color;

    return out;
}

@fragment
fn fs_main(in: VertexOutput) -> @location(0) vec4<f32> {
    // Softer Lambertian diffuse lighting for the strings
    let light_dir = normalize(vec3<f32>(1.0, 2.0, 1.0));
    let normal = normalize(in.normal);
    
    let diffuse = max(dot(normal, light_dir), 0.0);
    let ambient = 0.3;
    let light_intensity = diffuse * 0.7 + ambient;

    return vec4<f32>(in.color.rgb * light_intensity, 1.0);
}