// ==========================================
// SKELETON FOR NODE: arrow_render
// ==========================================

struct CameraStruct {
    viewProjection: mat4x4<f32>,
    view: mat4x4<f32>,
};

@group(0) @binding(0) var<uniform> camera: CameraStruct;
@group(0) @binding(1) var<storage, read> instances: array<f32>;
@group(0) @binding(2) var<storage, read> vertexData: array<f32>;

// ==========================================
// ARROW PARAMETERS
// ==========================================
// Configurable arrowhead size in world units.
const ARROW_HEAD_LENGTH: f32 = 0.15; 
// Must match the headLength parameter inside primitive.ts exactly (0.05)
const MESH_HEAD_LENGTH: f32 = 0.05;  

struct VertexOutput {
    @builtin(position) position: vec4<f32>,
    @location(0) normal: vec3<f32>,
    @location(1) color: vec4<f32>,
};

@vertex
fn vs_main(@builtin(vertex_index) v_idx: u32, @builtin(instance_index) i_idx: u32) -> VertexOutput {
    var out: VertexOutput;

    // 1. Read the raw vertex geometry
    let v_offset = v_idx * 6u;
    let v_pos = vec3<f32>(vertexData[v_offset], vertexData[v_offset + 1u], vertexData[v_offset + 2u]);
    let v_norm = vec3<f32>(vertexData[v_offset + 3u], vertexData[v_offset + 4u], vertexData[v_offset + 5u]);

    // 2. Read the 12 parameters generated by the compute shader
    let i_offset = i_idx * 12u;
    let pivot = vec3<f32>(instances[i_offset + 0u], instances[i_offset + 1u], instances[i_offset + 2u]);
    let vector = vec3<f32>(instances[i_offset + 3u], instances[i_offset + 4u], instances[i_offset + 5u]);
    let radius = instances[i_offset + 6u];
    // offset + 7u is padding
    let color = vec4<f32>(instances[i_offset + 8u], instances[i_offset + 9u], instances[i_offset + 10u], instances[i_offset + 11u]);

    // 3. Geometry Math
    let vec_len = length(vector);
    
    // Determine a safe actual head length (prevent head from being longer than the arrow itself)
    let actual_head_len = min(ARROW_HEAD_LENGTH, vec_len * 0.5);

    // To prevent the arrowhead from stretching, we map the Y coordinate non-linearly.
    // In makeArrowMesh, the shaft is Y: 0.0 -> 1.0, and the head is Y: 1.0 -> 1.0 + MESH_HEAD_LENGTH
    var local_y = v_pos.y;
    var scale_y = 1.0;

    if (local_y <= 1.0) {
        // We are on the shaft. Stretch it to fill the distance minus the arrowhead.
        local_y = local_y * (vec_len - actual_head_len);
        scale_y = vec_len - actual_head_len;
    } else {
        // We are on the head. Keep its proportions fixed.
        let head_t = (local_y - 1.0) / MESH_HEAD_LENGTH; // Normalize to 0.0 -> 1.0
        local_y = (vec_len - actual_head_len) + (head_t * actual_head_len);
        scale_y = actual_head_len / MESH_HEAD_LENGTH;
    }

    // Scale X and Z by the uniform radius
    let scaled_pos = vec3<f32>(v_pos.x * radius, local_y, v_pos.z * radius);

    // Because we scaled non-uniformly, we must correct the normals using the inverse scale
    let inv_scale = vec3<f32>(1.0 / radius, 1.0 / scale_y, 1.0 / radius);
    let scaled_norm = normalize(v_norm * inv_scale);

    // 4. Build the Rotation Matrix
    // The arrow mesh points UP (+Y). We want to align +Y to our vector.
    let Y_prime = vector / vec_len;
    
    // Robust cross-product base vector handling
    let helper_up = vec3<f32>(0.0, 0.0, 1.0);
    var X_prime = cross(Y_prime, helper_up);
    
    // Fallback if our vector is perfectly aligned with the Z-axis
    if (length(X_prime) < 0.001) {
        X_prime = normalize(cross(Y_prime, vec3<f32>(1.0, 0.0, 0.0)));
    } else {
        X_prime = normalize(X_prime);
    }
    
    let Z_prime = cross(X_prime, Y_prime);
    let rot_mat = mat3x3<f32>(X_prime, Y_prime, Z_prime);

    // 5. Rotate and move to the pivot point
    let world_pos = (rot_mat * scaled_pos) + pivot;
    let world_norm = rot_mat * scaled_norm;

    // 6. Transform to camera space
    out.position = camera.viewProjection * vec4<f32>(world_pos, 1.0);
    out.normal = (camera.view * vec4<f32>(world_norm, 0.0)).xyz;
    out.color = color;

    return out;
}

@fragment
fn fs_main(in: VertexOutput) -> @location(0) vec4<f32> {
    // Lambertian diffuse lighting
    let light_dir = normalize(vec3<f32>(1.0, 2.0, 1.0));
    let normal = normalize(in.normal);
    
    let diffuse = max(dot(normal, light_dir), 0.0);
    let ambient = 0.3;
    let light_intensity = diffuse * 0.7 + ambient;

    return vec4<f32>(in.color.rgb * light_intensity, in.color.a);
}
