// ==========================================
// AUTO-GENERATED SKELETON FOR NODE: bob_render
// ==========================================

struct CameraStruct {
    viewProjection: mat4x4<f32>,
    view: mat4x4<f32>,
};

@group(0) @binding(0) var<uniform> Camera: CameraStruct;
@group(0) @binding(1) var<storage, read> instances: array<f32>;
@group(0) @binding(2) var<storage, read> vertexData: array<f32>;

// ==========================================
// IMPLEMENT YOUR LOGIC BELOW
// ==========================================

struct VertexOutput {
    @builtin(position) position: vec4<f32>,
    @location(0) normal: vec3<f32>,
    @location(1) color: vec4<f32>,
};

@vertex
fn vs_main(@builtin(vertex_index) v_idx: u32, @builtin(instance_index) i_idx: u32) -> VertexOutput {
    var out: VertexOutput;

    // 1. Read the raw vertex geometry
    let v_offset = v_idx * 6u;
    let v_pos = vec3<f32>(vertexData[v_offset], vertexData[v_offset + 1u], vertexData[v_offset + 2u]);
    let v_norm = vec3<f32>(vertexData[v_offset + 3u], vertexData[v_offset + 4u], vertexData[v_offset + 5u]);

    // 2. Read the 8 parameters generated by the compute shader
    let i_offset = i_idx * 8u;
    let center = vec3<f32>(instances[i_offset + 0u], instances[i_offset + 1u], instances[i_offset + 2u]);
    let radius = instances[i_offset + 3u];
    let color = vec4<f32>(instances[i_offset + 4u], instances[i_offset + 5u], instances[i_offset + 6u], instances[i_offset + 7u]);

    // 3. Geometry Math (Scale & Translate only)
    let world_pos = (v_pos * radius) + center;
    
    // Since the sphere scales uniformly, the normal direction does not change
    let world_norm = v_norm;

    // 4. Transform to camera space
    out.position = Camera.viewProjection * vec4<f32>(world_pos, 1.0);
    out.normal = (Camera.view * vec4<f32>(world_norm, 0.0)).xyz;
    out.color = color;

    return out;
}

@fragment
fn fs_main(in: VertexOutput) -> @location(0) vec4<f32> {
    // Beautiful specular lighting for the spheres
    let light_dir = normalize(vec3<f32>(1.0, 2.0, 1.0));
    let view_dir = vec3<f32>(0.0, 0.0, 1.0); 
    
    let normal = normalize(in.normal);
    let diffuse = max(dot(normal, light_dir), 0.0);
    
    let half_vector = normalize(light_dir + view_dir);
    let specular = pow(max(dot(normal, half_vector), 0.0), 32.0);
    
    let ambient = 0.2;
    let light_intensity = diffuse * 0.7 + specular * 0.3 + ambient;

    return vec4<f32>(in.color.rgb * light_intensity, 1.0);
}