// ==========================================
// SKELETON FOR NODE: line_list_render
// ==========================================

struct CameraStruct {
    viewProjection: mat4x4<f32>,
    view: mat4x4<f32>,
};

@group(0) @binding(0) var<uniform> camera: CameraStruct;
@group(0) @binding(1) var<storage, read> instances: array<f32>;
// Mesh geometry (vertexData) is omitted because lines are procedurally generated from instances.

// ==========================================
// IMPLEMENT YOUR LOGIC BELOW
// ==========================================

struct VertexOutput {
    @builtin(position) position: vec4<f32>,
    @location(0) color: vec4<f32>,
};

@vertex
fn vs_main(@builtin(vertex_index) v_idx: u32, @builtin(instance_index) i_idx: u32) -> VertexOutput {
    var out: VertexOutput;

    // 1. Read the 12 parameters generated by the compute shader
    let i_offset = i_idx * 12u;
    let pivot = vec3<f32>(instances[i_offset + 0u], instances[i_offset + 1u], instances[i_offset + 2u]);
    let vector = vec3<f32>(instances[i_offset + 3u], instances[i_offset + 4u], instances[i_offset + 5u]);
    // instances[i_offset + 6u] is radius (unused because WebGPU native lines are 1px)
    // instances[i_offset + 7u] is padding
    let color = vec4<f32>(instances[i_offset + 8u], instances[i_offset + 9u], instances[i_offset + 10u], instances[i_offset + 11u]);

    // 2. Procedural Line Geometry
    // A line-list draws a segment between pairs of vertices. 
    // Since we draw 2 vertices per instance, v_idx will be 0 or 1.
    var world_pos: vec3<f32>;
    if (v_idx == 0u) {
        world_pos = pivot;              // Start of the line
    } else {
        world_pos = pivot + vector;     // End of the line
    }

    // 3. Transform to camera space
    out.position = camera.viewProjection * vec4<f32>(world_pos, 1.0);
    out.color = color;

    return out;
}

@fragment
fn fs_main(in: VertexOutput) -> @location(0) vec4<f32> {
    // Flat Shading
    // Like point-lists, 1-pixel lines do not have surface area to calculate normals
    // or standard lighting models. We output the raw color.
    return in.color;
}